CREATE DATABASE IF NOT EXISTS userdb;
USE userdb;
CREATE TABLE IF NOT EXISTS user (
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    user char(25) NOT NULL,
    password char(25) NOT NULL,
    UNIQUE (user)
) ENGINE=InnoDB;
CREATE USER IF NOT EXISTS 'userdb'@'%' IDENTIFIED BY 'userdb';
GRANT ALL PRIVILEGES ON userdb.* TO 'userdb'@'%';
FLUSH PRIVILEGES;
